"""
Telegram notification system for the Polymarket trading bot.

Sends real-time alerts via a Telegram bot for:
- Trade signals generated by any agent
- Orders placed or cancelled (dry-run flagged appropriately)
- Risk limit breaches
- Nightly postmortem summaries
- Bot startup / shutdown events

Uses python-telegram-bot in async mode. Bot token and chat ID are loaded
from environment variables TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID.
"""

import os
from typing import Optional


class TelegramAlerter:
    """Async Telegram notification client."""

    def __init__(self, token: Optional[str] = None, chat_id: Optional[str] = None):
        self.token = token or os.getenv("TELEGRAM_BOT_TOKEN")
        self.chat_id = chat_id or os.getenv("TELEGRAM_CHAT_ID")
        self._bot = None  # initialized lazily

    async def send(self, message: str) -> None:
        """Send a plain-text message to the configured chat."""
        raise NotImplementedError

    async def send_trade_signal(self, agent: str, market: str, side: str, confidence: float) -> None:
        """Format and send a trade signal alert."""
        raise NotImplementedError

    async def send_postmortem_summary(self, report_path: str) -> None:
        """Send the nightly postmortem summary extracted from the report file."""
        raise NotImplementedError

    async def close(self) -> None:
        """Gracefully close the underlying bot connection."""
        raise NotImplementedError
